module.exports = {
  EVENT_ALREADY_TAKEN: 0,
  BLANK_NAME: 1,
  INVALID_NAME_LENGTH: 2,
  BLANK_SECOND_NAME: 3,
  INVALID_SECOND_NAME_LENGTH: 4,
  BLANK_PATRONYMIC: 5,
  INVALID_PATRONYMIC_LENGTH: 6,
  BLANK_USERNAME: 7,
  INVALID_USERNAME_LENGTH: 8,
  BLANK_PASSWORD: 9,
  INVALID_PASSWORD_LENGTH: 10,
  NAME_IS_NOT_A_STRING: 11,
  SECOND_NAME_IS_NOT_A_STRING: 12,
  PATRONYMIC_IS_NOT_A_STRING: 13,
  USERNAME_IS_NOT_A_STRING: 14,
  PASSWORD_IS_NOT_A_STRING: 15
}